version: '3.3'
services:
  #   redis:
  #     image: redis:latest
  #     container_name: redis
  #     restart: always
  #     volumes:
  #       - redis_volume_data:/data
  #     ports:
  #       - 6379:6379
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=example
    ports:
      - 6379:6379
#   redis_insight:
#     image: redislabs/redisinsight:latest
#     container_name: redis_insight
#     restart: always
#     ports:
#       - 8001:8001
#     volumes:
#       - redis_insight_volume_data:/db

# volumes:
#   redis_volume_data:
#   redis_insight_volume_data:
